<?php

    // Get Custom Category Atribute "Short Description"

    $shortDesc = $block->getCurrentCategory()->getShortDescLong();

?>



<?php if ($shortDesc) :?>

<div class="description-wrap">

    <div class="category-description">

        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(

            $block->getCurrentCategory(),

            $shortDesc,

            'description'

        ) ?>

    </div>



    <?php

    $_category  = $block->getCurrentCategory();

    $_imgHtml   = '';

    if ($_imgUrl = $block->getImage()->getUrl($_category)) {

        $_imgHtml = '<div class="category-image"><img src="'

            . $block->escapeUrl($_imgUrl)

            . '" alt="'

            . $block->escapeHtmlAttr($_category->getName())

            . '" title="'

            . $block->escapeHtmlAttr($_category->getName())

            . '" class="image" /></div>';

        $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');

        //echo $_imgHtml;

    } 

	?>

</div>

<?php endif; ?>



