<div class="titlesection">
    <h1>Contact Us</h1>
    <p>Barons friendly sales team are on hand to answer any of your questions or product enquiries. Simply contact us using the form below or give us a call and we will be happy to help. You can also use our form below to book a visit from our unique display van service, or an appointment in our showroom</p>
</div>



<div class="content-form-area">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-6 borderright">
                <div class="row">
                    <div class="col offset-md-2">
                        <h3>Contact Details</h3>
                        <p style="margin-bottom:0;">01254 741940</p>
                        <p>sales@baronsfurniture.co.uk</p>
                        <p>4&5 Lidun Park Industrial Estate,</br> Boundary Road,</br> Lytham FY8 5HU</p>

                        <h3 class="pt40">Regional Sales Managers</h3>

                        <ul class="team">
                                
                            <li>
                                <img src="https://baronsfurniture.piranha.digital/wp/wp-content/uploads/2022/05/dean-booth-asm.png" alt="dean-booth-asm">
                                <h4>Dean Booth</h4>
                                <h5>North England, North Wales & the Midlands</h5>
                                <p><a href="">CONTACT DEAN</a></p>
                            </li>
                            <li>
                                <img src="https://baronsfurniture.piranha.digital/wp/wp-content/uploads/2022/05/ian-mcintosh-asm.png" alt="ian-mcintosh-asm">
                                <h4>Ian McIntosh</h4>
                                <h5>Scotland & North East England</h5>
                                <p><a href="">CONTACT Ian</a></p>
                            </li>
                            <li>
                                <img src="https://baronsfurniture.piranha.digital/wp/wp-content/uploads/2022/05/martyn-dunn-asm.png" alt="martyn-dunn">
                                <h4>Martyn Dunn</h4>
                                <h5>South East England</h5>
                                <p><a href="">CONTACT Martyn</a></p>
                            </li>
                            <li>
                                <img src="https://baronsfurniture.piranha.digital/wp/wp-content/uploads/2022/05/lawrence-easley-asm.png" alt="lawrence-easley-asm">
                                <h4>Lawrence Easley</h4>
                                <h5>South West England & South Wales</h5>
                                <p><a href="">CONTACT Lawrence</a></p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="map">
                    <h3 class="title">Visit Us <a href="#">Get Directions</a></h3>





                    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>

<div id="map" class="map desk-three-forth"></div>
<script>
var map,
desktopScreen = Modernizr.mq( "only screen and (min-width:1024px)" ),
zoom = desktopScreen ? 18 : 17,
scrollable = draggable = !Modernizr.hiddenscroll || desktopScreen,
isIE11 = !!(navigator.userAgent.match(/Trident/) && navigator.userAgent.match(/rv[ :]11/));
function initMap() {
var myLatLng = {lat: 53.74706120189789, lng:-2.9375081332256174};
map = new google.maps.Map(document.getElementById('map'), {
zoom: 16,
minZoom:1,
center: myLatLng,
mapTypeId: google.maps.MapTypeId.ROADMAP,
scrollwheel: scrollable,
draggable: draggable,
});
var locations = [
{
title: 'Barons',
position: {lat: 53.74706120189789, lng:-2.9375081332256174},
icon: {
scaledSize: new google.maps.Size(50, 50)
}
}
];
locations.forEach( function( element, index ){
var marker = new google.maps.Marker({
position: element.position,
map: map,
title: element.title,
icon: element.icon,
});
});
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDz2KocEvcEq18y-gporhQ8GLLWqv7ogx4&callback=initMap"
    async defer></script>






                </div>


            </div>

            <div class="col-md-4  offset-md-1">
                <h3>Enquiry</h3>


            <div class="contact-form">
      
                <?php echo apply_shortcodes( '[contact-form-7 id="5" title="Contact form 1"]' ); ?>

            </div>


            
              


            </div>

        </div>
    </div>



</div>