<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<?php if ($post = $block->getPost()): ?>
    <div class="post-list-item">
    
        <?php if (!$post->isViewableForVisitor()): ?>
            <?= $block->getPasswordProtectHtml() ?>
        <?php else: ?>
            <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtmlAttr($post->getName()) ?>">
                <div class="post-entry">
                    <?php if ($image = $post->getImage()): ?>
                        <?php $imageUrl = $image->getResizer() // Resizing only available in local integration mode
                                ? $image->getResizer()->constrainOnly(true)
                                    ->keepFrame(false)
                                    ->keepAspectRatio(true)
                                    ->resize(600, null)
                                : $image->getImageUrl(['large', 'medium']) ?>
                        <div class="post-image" style="background-image:url('<?= $block->escapeUrl($imageUrl) ?>');">
                        
                        </div>
                    <?php endif; ?>
                </div>
            </a>
        <?php endif; ?>


        <div class="content-area">
            <h2>
                <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtmlAttr($post->getName()) ?>">
                    <?= $block->escapeHtml($post->getName()) ?>
                </a>
            </h2>

            <!-- <div class="post-excerpt"><?= /* @noEscape */ $post->getExcerpt(60) ?></div> -->


            <div class="post-meta">
        
                <div class="post-date post-meta-item">
                    <?= $block->escapeHtml($post->getPostDate()) ?>
                </div>
            
            </div>
        </div>



    </div>
<?php endif; ?>