<div class="topbar">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">

            </div>
            <div class="col-md-8">
                <p>MADE FOR LIVING</p>
            </div>
            <div class="col-md-2">
                <ul>
                    <li><a href="/display-van/">DISPLAY VAN</a></li>
                    <li><a href="/showroom/">SHOWROOM</a></li>
                </ul>
            </div>
        </div>
    </div>

</div>